services:
  postgres_db:
    image: postgres:16-alpine
    container_name: tree_db
    environment:
      POSTGRES_USER: tree-dba
      POSTGRES_PASSWORD: tree-dba
      POSTGRES_DB: tree-db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U tree-dba -d tree-db" ]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    image: api
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: tree_api
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__DefaultConnection: Host=postgres_db;Port=5432;Database=tree-db;Username=tree-dba;Password=tree-dba
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      postgres_db:
          condition: service_healthy

volumes:
  db_data: